export const categoriesList = [
  { title: "Accessories", targetScreen: "ProfileInformation" },
  { title: "Art", targetScreen: "Messages" },
  { title: "Beauty", targetScreen: "Reviews" },
  { title: "Books", targetScreen: "AccountSettings" },
  { title: "Kids", targetScreen: "FAQ" },
  { title: "Clothes", targetScreen: "CustomerService" },
  { title: "Computers", targetScreen: "Terms" },
  { title: "Construction", targetScreen: "ProfileInformation" },
  { title: "Electronics", targetScreen: "Messages" },
  { title: "Households", targetScreen: "Reviews" },
  { title: "Jewelries", targetScreen: "AccountSettings" },
  { title: "Phones", targetScreen: "FAQ" },
  { title: "Men", targetScreen: "FAQ" },
  { title: "Music", targetScreen: "CustomerService" },
  { title: "Photo & Camera", targetScreen: "Terms" },
  { title: "Shoes", targetScreen: "Terms" },
  { title: "Sports", targetScreen: "ProfileInformation" },
  { title: "Travel", targetScreen: "Messages" },
  { title: "Toys", targetScreen: "Reviews" },
  { title: "Vehicles", targetScreen: "AccountSettings" },
  { title: "Computer Games", targetScreen: "FAQ" },
  { title: "Watches", targetScreen: "CustomerService" },
  { title: "Women", targetScreen: "CustomerService" },
];
